// sleeper/src/components/UserLogin.svelte
<!--
    UserLogin.svelte
    component used to retrieve user info
-->

<script>
    import "../base.css";
    import {
        get_user,
        get_user_current_leagues,
    } from "../api.js";
    import {
        loading,
        user_leagues,
    } from "../stores.js";

    let username_input;

    async function on_submit(event) {
        event.preventDefault();
        loading.set(true);

        // get the user data for the given username
        let username = username_input.value;
        console.log(`searching for user ${username}`);
        let user_data = await get_user(username);
        if (user_data) {
            // get the leagues data from the current year for the user
            console.log(`searching for leagues for user ${user_data.user_id}`);
            let user_league_data = await get_user_current_leagues(user_data.user_id);
            if (user_league_data) {
                user_leagues.set(user_league_data);
            }
        } else {
            alert(`failed to find user "${username}"`);
        }
        loading.set(false);
    }
</script>

<form id="user-input" class="vflex" on:submit={on_submit}>
    <label for="username">Enter your username:</label>
    <input type="text" id="username-input" required bind:this={username_input}>
    <button id="user-button">submit</button>
</form>

<style>
    #user-input {
        font-size: 14px;
        justify-content: flex-start;
        gap: 8px;
    }

    #username-input {
        width: 256px;
    }

    #user-button {
        font-size: 14px;
        align-self: center;
        padding: 2px 16px;
        margin: 4px;
    }
</style>

// sleeper/src/components/UserLogin.tsx
/*
** sleeper/src/components/UserLogin.tsx
*/

import React from "react";

import { League, getUserID, getUserCurrentLeagues } from "../api.ts";
import LoadingBar from "./LoadingBar.tsx";
import "../styles/UserLogin.css";

interface UserLoginProps {
    setLeagues: React.Dispatch<React.SetStateAction<League[]>>;
    nextPage: () => void;
}

export default function UserLogin({ setLeagues, nextPage }: UserLoginProps) {
    const [username, setUsername] = React.useState("");
    const [loading, setLoading] = React.useState(false);

    function onUsernameChange(event: React.ChangeEvent<HTMLInputElement>) {
        setUsername(event.target.value);
    }

    async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
        let userID: string;
        let userLeagues: League[];

        event.preventDefault();
        if (username.length == 0) {
            return;
        }
        setLoading(true);

        // get the user ID for the given username
        try {
            userID = await getUserID(username);
            console.debug(`${username} ID: ${userID}`);
        } catch {
            alert(`Failed to find user "${username}"`);
            setLoading(false);
            return;
        }

        // get the leagues data from the current year for the user
        try {
            userLeagues = await getUserCurrentLeagues(userID);
            console.debug(`${username} leagues:`, userLeagues);
        } catch {
            alert(`Failed to retrieve Sleeper leagues for ${username}`);
            setLoading(false);
            return;
        }

        setLeagues(userLeagues);
        nextPage();
    }

    return (
        <form className="user-input" onSubmit={onSubmit}>
            <label>Enter your username:</label>
            <input
                type="text"
                className="username-input"
                value={username}
                onChange={onUsernameChange}
            />
            <button className="user-button">submit</button>
            <LoadingBar loading={loading}/>
        </form>
    );
}
