// sleeper/src/components/LeagueStatsView.tsx
/*
** sleeper/src/components/LeagueStatsView.tsx
*/

import React from "react";

import { Info, userIdToName } from "../utils.ts";
import GameStatView from "./GameStatView.tsx";
import StatsListView from "./StatsListView.tsx";
import "../styles/LeagueStatsView.css";

interface LeagueStatsViewProps {
    info: Info;
}

export default function LeagueStatsView({ info }: LeagueStatsViewProps) {
    const currentYear = new Date().getFullYear();
    const leagueName = info.league[currentYear].name;

    /*
    ** win percentage
    */
    const winPctHeaders = ["Name", "W", "L", "Pct"];
    const winPct: any[] = [];
    for (const [userID, stats] of Object.entries(info.matchups.users)) {
        winPct.push({
            name: userIdToName(info.users, userID),
            wins: stats.wins,
            losses: stats.losses,
            winPct: (stats.wins / (stats.wins + stats.losses)) * 100,
            pointsFor: stats.pointsFor,  // used as a tiebreaker
        });
    }
    // reverse-sort to get descending order
    winPct.sort((a, b) => {
        if (a.wins == b.wins) {
            // use points_for to break ties
            return a.pointsFor - b.pointsFor;
        } else {
            return a.wins - b.wins;
        }
    }).reverse();
    // transform into the expected StatsListView format
    const winPctEntries = winPct.map((o) => (
        [o.name, o.wins, o.losses, `${o.winPct.toFixed(1)}%`]
    ));

    /*
    ** points scored
    */
    const pointsScoredHeaders = ["Name", "PF"];
    const pointsScored: any[] = [];
    for (const [userID, stats] of Object.entries(info.matchups.users)) {
        pointsScored.push({
            name: userIdToName(info.users, userID),
            pointsFor: stats.pointsFor,
        });
    }
    // reverse-sort to get descending order
    pointsScored.sort((a, b) => a.pointsFor - b.pointsFor).reverse();
    const pointsScoredEntries = pointsScored.map((o) => (
        [o.name, o.pointsFor.toFixed(2)]
    ));

    /*
    ** points against
    */
    const pointsAgainstHeaders = ["Name", "PA"];
    const pointsAgainst: any[] = [];
    for (const [userID, stats] of Object.entries(info.matchups.users)) {
        pointsAgainst.push({
            name: userIdToName(info.users, userID),
            pointsAgainst: stats.pointsAgainst,
        });
    }
    pointsAgainst.sort((a, b) => a.pointsAgainst - b.pointsAgainst);
    const pointsAgainstEntries = pointsAgainst.map((o) => (
        [o.name, o.pointsAgainst.toFixed(2)]
    ));

    /*
    ** bench points
    */
    const benchPointsHeaders = ["Name", "Pts"];
    const benchPoints: any[] = [];
    for (const [userID, stats] of Object.entries(info.matchups.users)) {
        benchPoints.push({
            name: userIdToName(info.users, userID),
            benchPoints: stats.benchPoints,
        });
    }
    // reverse-sort to get descending order
    benchPoints.sort((a, b) => a.benchPoints - b.benchPoints).reverse();
    const benchPointsEntries = benchPoints.map((o) => (
        [o.name, o.benchPoints.toFixed(2)]
    ));

    /*
    ** trades completed
    */
    const tradesCompletedHeaders = ["Name", "Trades"];
    const tradesCompleted: any[] = [];
    for (const [userID, stats] of Object.entries(info.transactions)) {
        tradesCompleted.push({
            name: userIdToName(info.users, userID),
            tradesCompleted: stats.tradesCompleted,
        });
    }
    // reverse-sort to get descending order
    tradesCompleted.sort((a, b) => a.tradesCompleted - b.tradesCompleted).reverse();
    const tradesCompletedEntries = tradesCompleted.map((o) => [o.name, o.tradesCompleted]);

    /*
    ** player transactions
    */
    const transactionsHeaders = ["Name", "Txns"];
    const transactions: any[] = [];
    for (const [userID, stats] of Object.entries(info.transactions)) {
        transactions.push({
            name: userIdToName(info.users, userID),
            transactions: stats.playerTransactions,
        });
    }
    // reverse-sort to get descending order
    transactions.sort((a, b) => a.transactions - b.transactions).reverse();
    const transactionsEntries = transactions.map((o) => [o.name, o.transactions]);

    /*
    ** FAAB spent
    */
    const faabSpentHeaders = ["Name", "FAAB"];
    const faabSpent: any[] = [];
    for (const [userID, stats] of Object.entries(info.transactions)) {
        faabSpent.push({
            name: userIdToName(info.users, userID),
            faabSpent: stats.faabSpent,
        });
    }
    // reverse-sort to get descending order
    faabSpent.sort((a, b) => a.faabSpent - b.faabSpent).reverse();
    const faabSpentEntries = faabSpent.map((o) => [o.name, `$${o.faabSpent}`]);

    return (
        <section className="league-stats-wrapper">
            <p className="title">{leagueName}</p>
            <div className="stats-views-wrapper">
                <GameStatView
                    info={info}
                    title="MOST POINTS"
                    game={info.matchups.maxScore}
                    boldWinner={true}
                />
                <GameStatView
                    info={info}
                    title="LEAST POINTS"
                    game={info.matchups.minScore}
                    boldLoser={true}
                />
                <GameStatView
                    info={info}
                    title="BIGGEST BLOWOUT"
                    game={info.matchups.biggestBlowout}
                />
                <GameStatView
                    info={info}
                    title="CLOSEST GAME"
                    game={info.matchups.closestGame}
                />
                <div className="grid-break"/>
                <StatsListView
                    title="WIN PERCENTAGE"
                    headers={winPctHeaders}
                    entries={winPctEntries}
                />
                <StatsListView
                    title="TOTAL POINTS SCORED"
                    headers={pointsScoredHeaders}
                    entries={pointsScoredEntries}
                />
                <StatsListView
                    title="TOTAL POINTS AGAINST"
                    headers={pointsAgainstHeaders}
                    entries={pointsAgainstEntries}
                />
                <StatsListView
                    title="TOTAL BENCH POINTS"
                    headers={benchPointsHeaders}
                    entries={benchPointsEntries}
                />
                <StatsListView
                    title="TOTAL TRADES COMPLETED"
                    headers={tradesCompletedHeaders}
                    entries={tradesCompletedEntries}
                />
                <StatsListView
                    title="TOTAL FA/WAIVER MOVES"
                    headers={transactionsHeaders}
                    entries={transactionsEntries}
                />
                <StatsListView
                    title="TOTAL FAAB SPENT"
                    headers={faabSpentHeaders}
                    entries={faabSpentEntries}
                />
            </div>
        </section>
    );
}

// src/sleeper/components/LeagueStatsView.svelte
<!--
    LeagueStatsView.svelte
    displays a progress bar for the API queries
-->

<script>
    import "../base.css";
    import { league_info } from "../stores.js";
    import {
        get_matchup_stats,
        get_per_user_matchup_stats,
        get_transaction_stats,
        user_id_to_name,
    } from "../utils.js";

    import GameStatView from "./GameStatView.svelte";
    import StatsListView from "./StatsListView.svelte";

    // post-process some of the league data
    let matchup_stats = get_matchup_stats($league_info);
    let per_user_matchup_stats = get_per_user_matchup_stats($league_info);
    let transaction_stats = get_transaction_stats($league_info);

    // FIXME: DEBUG
    console.log($league_info);
    console.log(matchup_stats);
    console.log(per_user_matchup_stats);
    console.log(transaction_stats);

    function get_league_name() {
        let current_year = new Date().getFullYear();
        return $league_info.years[current_year].info.name;
    }

    function get_win_pct_ratings(stats) {
        let headers = ["Name", "W", "L", "Pct"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats.users)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                wins: user_stats.wins,
                losses: user_stats.losses,
                win_pct: (user_stats.wins / (user_stats.wins + user_stats.losses)) * 100,
                // include points_for so that it can be used as a tiebreaker
                points_for: user_stats.points_for,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => {
            if (a.wins == b.wins) {
                // use points_for to break ties
                return a.points_for - b.points_for;
            } else {
                return a.wins - b.wins;
            }
        }).reverse();
        // transform into the expected StatsListView format
        entries = entries.map((o) => {
            return [o.name, o.wins, o.losses, `${o.win_pct.toFixed(1)}%`];
        });
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_points_scored_ratings(stats) {
        let headers = ["Name", "PF"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats.users)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                points_for: user_stats.points_for,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => a.points_for - b.points_for).reverse();
        entries = entries.map((o) => [o.name, o.points_for.toFixed(2)]);
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_points_against_ratings(stats) {
        let headers = ["Name", "PA"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats.users)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                points_against: user_stats.points_against,
            });
        }
        entries.sort((a, b) => a.points_against - b.points_against);
        entries = entries.map((o) => [o.name, o.points_against.toFixed(2)]);
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_bench_points_ratings(stats) {
        let headers = ["Name", "Pts"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats.users)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                bench_points: user_stats.bench_points,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => a.bench_points - b.bench_points).reverse();
        entries = entries.map((o) => [o.name, o.bench_points.toFixed(2)]);
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_trades_completed_ratings(stats) {
        let headers = ["Name", "Trades"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                trades_completed: user_stats.trades_completed,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => a.trades_completed - b.trades_completed).reverse();
        entries = entries.map((o) => [o.name, o.trades_completed]);
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_player_transactions_ratings(stats) {
        let headers = ["Name", "Txns"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                transactions: user_stats.player_transactions,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => a.transactions - b.transactions).reverse();
        entries = entries.map((o) => [o.name, o.transactions]);
        return {
            headers: headers,
            entries: entries,
        };
    }

    function get_faab_spent_ratings(stats) {
        let headers = ["Name", "FAAB"];
        let entries = [];
        for (const [user_id, user_stats] of Object.entries(stats)) {
            entries.push({
                name: user_id_to_name($league_info.users, user_id),
                faab_spent: user_stats.faab_spent,
            });
        }
        // reverse-sort to get descending order
        entries.sort((a, b) => a.faab_spent - b.faab_spent).reverse();
        entries = entries.map((o) => [o.name, `$${o.faab_spent}`]);
        return {
            headers: headers,
            entries: entries,
        };
    }
</script>

<section id="league-stats-wrapper">
    <p class="title">{get_league_name()}</p>
    <div id="stats-views-wrapper" class="hflex">
        <GameStatView
            title="MOST POINTS"
            game={matchup_stats.max_score}
            bold_winner={true}
        />
        <GameStatView
            title="LEAST POINTS"
            game={matchup_stats.min_score}
            bold_loser={true}
        />
        <GameStatView
            title="BIGGEST BLOWOUT"
            game={matchup_stats.biggest_blowout}
        />
        <GameStatView
            title="CLOSEST GAME"
            game={matchup_stats.closest_game}
        />
        <div class="grid-break"></div>
        <StatsListView
            title="WIN PERCENTAGE"
            {...get_win_pct_ratings(matchup_stats)}
        />
        <StatsListView
            title="TOTAL POINTS SCORED"
            {...get_points_scored_ratings(matchup_stats)}
        />
        <StatsListView
            title="TOTAL POINTS AGAINST"
            {...get_points_against_ratings(matchup_stats)}
        />
        <StatsListView
            title="TOTAL BENCH POINTS"
            {...get_bench_points_ratings(matchup_stats)}
        />
        <StatsListView
            title="TOTAL TRADES COMPLETED"
            {...get_trades_completed_ratings(transaction_stats)}
        />
        <StatsListView
            title="TOTAL FA/WAIVER MOVES"
            {...get_player_transactions_ratings(transaction_stats)}
        />
        <StatsListView
            title="TOTAL FAAB SPENT"
            {...get_faab_spent_ratings(transaction_stats)}
        />
    </div>
</section>

<style>
    #league-stats-wrapper {
        width: 100%;
        height: 100%;
    }

    .title {
        font-size: 24px;
        margin: 0;
        margin-bottom: 32px;
    }

    #stats-views-wrapper {
        flex-wrap: wrap;
        column-gap: 64px;
    }

    .grid-break {
        flex-basis: 100%;
        height: 0;
    }

    @media only screen and (max-width: 768px) {
        .title {
            font-size: 20px;
            margin-bottom: 16px;
        }
    }
</style>
