// sleeper/src/components/StatsListView.tsx
/*
** sleeper/src/components/StatsListView.tsx
*/

import React from "react";

import "../styles/StatsListView.css";

interface StatsListViewProps {
    title: string;
    headers: string[];
    entries: string[][];
}

export default function StatsListView({ title, headers, entries }: StatsListViewProps) {
    const gridLayout = {
        gridTemplateColumns: `repeat(${headers.length + 1}, auto)`,
        gridTemplateRows: `repeat(${entries.length + 1}, auto)`,
    };

    let key = 0;
    const items: React.ReactElement[] = [];
    items.push(<p key={key++} className="grid-header">#</p>);
    headers.forEach((header) => {
        items.push(<p key={key++} className="grid-header">{header}</p>);
    });
    entries.forEach((entry, i) => {
        items.push(<p key={key++} className="grid-item-index">{i + 1}</p>);
        entry.forEach((field, j) => {
            const className = j == 0 ? "grid-item-name" : "grid-item";
            items.push(<p key={key++} className={className}>{field}</p>);
        });
    });

    return (
        <div className="stats-list-wrapper">
            <p className="stats-list-title">{title}</p>
            <div className="stats-list-grid" style={gridLayout}>
                {items}
            </div>
        </div>
    );
}

// src/sleeper/components/StatsListView.svelte
<!--
    StatsListView.svelte
    displays a ranked list of statistics
-->

<script>
    import "../base.css";

    export let title;
    export let headers;
    export let entries;

    function grid_layout_style() {
        let cols = `grid-template-columns: repeat(${headers.length + 1}, auto)`;
        let rows = `grid-template-rows: repeat(${entries.length + 1}, auto)`;
        return `${cols}; ${rows}`;
    }
</script>

<div class="stats-list-wrapper vflex">
    <p class="stats-list-title">{title}</p>
    <div class="stats-list-grid" style={grid_layout_style()}>
        <!-- empty header item for the index -->
        <p class="grid-header"></p>
        {#each headers as header}
            <p class="grid-header">{header}</p>
        {/each}
        {#each entries as entry, i}
            <p class="grid-item-index">{i + 1}</p>
            {#each entry as field, j}
                {#if j == 0}
                    <p class="grid-item-name">{field}</p>
                {:else}
                    <p class="grid-item">{field}</p>
                {/if}
            {/each}
        {/each}
    </div>
</div>

<style>
    .stats-list-wrapper {
        font-size: 14px;
    }

    .stats-list-title {
        font-weight: 600;
        margin: 4px 0;
        margin-left: 2.5em;
    }

    .stats-list-grid {
        display: grid;
        column-gap: 16px;
        row-gap: 2px;
    }

    .grid-header {
        font-weight: 600;
        margin: 4px 0;
        text-align: right;
    }

    .grid-header:nth-child(2) {
        text-align: left;
    }

    .grid-item-index {
        font-size: 12px;
        margin: 0;
        margin-right: 4px;
        text-align: right;
        vertical-align: center;
        height: 100%;
    }

    .grid-item {
        margin: 0;
        text-align: right;
    }

    .grid-item-name {
        margin: 0;
        text-align: left;
    }
</style>
